04-11 09:43:23 imba: True
04-11 09:43:23 model_name: ACDANN
04-11 09:43:23 Domain: CWRU
04-11 09:43:23 source: CWRU_3
04-11 09:43:23 target: CWRU_0
04-11 09:43:23 data_dir: ./datasets
04-11 09:43:23 train_mode: single_source
04-11 09:43:23 cuda_device: 0
04-11 09:43:23 save_dir: ./ckpt
04-11 09:43:23 max_epoch: 30
04-11 09:43:23 batch_size: 64
04-11 09:43:23 num_workers: 0
04-11 09:43:23 signal_size: 2048
04-11 09:43:23 random_state: 2024
04-11 09:43:23 normlizetype: mean-std
04-11 09:43:23 opt: sgd
04-11 09:43:23 lr: 0.01
04-11 09:43:23 momentum: 0.9
04-11 09:43:23 betas: (0.9, 0.999)
04-11 09:43:23 weight_decay: 0.0005
04-11 09:43:23 lr_scheduler: stepLR
04-11 09:43:23 gamma: 0.2
04-11 09:43:23 steps: 10
04-11 09:43:23 tradeoff: ['exp', 'exp', 'exp']
04-11 09:43:23 dropout: 0.0
04-11 09:43:23 save: False
04-11 09:43:23 load_path: 
04-11 09:43:23 save_path: ./ckpt/ACDANN/single_source/[CWRU_3]To[CWRU_0]_0411-094323
04-11 09:43:23 Detect 4 classes: ['ball', 'inner', 'normal', 'outer']
04-11 09:43:23 using 1 / 1 gpus
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    trainer = importlib.import_module(f"models.{args.model_name}").Trainset(args)
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/models/ACDANN.py", line 30, in __init__
    self._init_data()
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/train_utils.py", line 102, in _init_data
    self.datasets[source] = Dataset(data_root, src, args.faults, args.signal_size, args.normlizetype, condition=condition
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/data_loader/data_load.py", line 68, in __init__
    self.train_data, self.train_labels,self.test_data,self.test_labels = get_files(root=data_dir, dataset=dataset, faults=faults, signal_size=signal_size, condition=condition)
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/data_loader/data_load.py", line 17, in get_files
    for item in os.listdir(data_dir):
FileNotFoundError: [Errno 2] No such file or directory: './datasets/CWRU/condition_3/ball'
